CREATE OR REPLACE VIEW hcrs.int_intrfc_1216_v
AS
   SELECT
   /****************************************************************************
   *    View Name : int_intrfc_1216_v
   * Date Created : 09/01/2009
   *       Author : Joe Kidd
   *  Description : Translates icw2_intrpd_credits_v into mstr_trans_stg_t for
   *                Interface 1216.
   *
   *                Note: There will be no SAP4H transactions from Interpreted
   *                Credits, but translations have been added for possible
   *                future use.
   *
   *                Scalar subqueries return pkg_qty, claim_unit_qty, and
   *                gross_sales_amt fields as a single pipe-delimited varchar
   *                to reduce the number of subquery executions.  An object type
   *                was considered, but caused the query to execute locally
   *                instead of on the remote db, resulting in poor performance.
   *
   * MOD HISTORY
   *  Date        Modified by   Reason
   *  ----------  ------------  ------------------------------------------------
   *  01/27/2010  Joe Kidd      RT 2009-372 - IS-000000000018 - Prasco/Winthrop Initiative
   *                            Added src_tbl_cd field
   *  07/09/2010  Joe Kidd      CRQ 44095 - July 2010 GPCS Interface Release
   *                            Add prompt payment for credits
   *  08/09/2010  Joe Kidd      CRQ-50196: August 2010 GPCS Interface Release
   *                            Limit to US companies
   *  03/01/2011  Joe Kidd      CRQ-2196: Load ICW Related Credit Number
   *                            Add related credits id field
   *  09/14/2011  Joe Kidd      CRQ-10164: Genzyme GP Integration Phase 1 part 1
   *                            Add Line Ref ID and WAC price fields
   *                            Add NO_MERGE hint to inner query
   *  03/02/2012  Joe Kidd      CRQ-13227: Genzyme GP Integration Phase 1 part 2
   *                            Change Company limit from include to exclude list
   *                            Easier to delete extra trans that add missing trans
   *  04/01/2012  Joe Kidd      CRQ-20492: Genzyme GP Integration Phase 2 part 1
   *                            Change NO_MERGE hint to DRIVING_SITE hint
   *  07/05/2012  Joe Kidd      CRQ-24537: Genzyme GP Integration Phase 2 part 2
   *                            Block Genzyme legacy data rebates created for SPM only
   *                            Add keys for Genzyme legacy data
   *                            Add fields to allow searching directly on this view
   *  09/25/2012  Joe Kidd      CRQ-31332: GP Methodology Harmonization
   *                            Reorg fields based on new staging/prod table
   *  11/01/2012  Joe Kidd      CRQ-31333: Sklice GP Integration
   *                            Rename views with new interface IDs
   *  10/17/2014  Joe Kidd      CRQ-131909: Demand 2849 Bundling of SAP Direct Sales
   *                            Add WAC price and WAC extended amount columns
   *                            Support reloading transactions
   *                            Populate pkgs and gross dollars for rebates/fees
   *                            generated by chargebacks
   *  07/17/2018  Joe Kidd      CHG-0055804: Demand 6812 SURF BSI / Cust COT
   *                            Remove Contract ID match for CARS/RMUS lookup
   *                            of gross dollars/units from Chgbks/Util/CustSales
   *  03/01/2019  Deepak Gupta  CHG0123872: SHIFT BSI
   *                            Support SAP4H transactions, add term code, add
   *                            original invoice source system, and others for
   *                            support queries
   *  08/01/2020  Joe Kidd      CHG-0000000: Bioverativ Integration
   *                            Add Bioverative RxC Direct Credits, CCG Rebates,
   *                            and Biogen Medicaid
   *  08/25/2020  Pravin Hujare CHG-0000000: SHIFT PHASE 2
   *                            Add company code PR02 to the list of blocked company codes
   ****************************************************************************/
          -- ICW Fields (needed for interface queries)
          z.credit_num,
          z.created_dte,
          z.credit_dte,
          z.ndc_cde,
          -- ICW Fields (added for support queries)
          z.type_cde,
          z.reasn_cde,
          z.paidto_cust_id,
          z.mbr_id,
          z.contr_ownr_id,
          z.contr_id_sale,
          z.contr_ownr_id_sale,
          z.cpgrp_num,
          z.amt,
          z.intrpd_term_disc_pct,
          z.po_dte,
          z.invce_num,
          z.invce_line_num,
          z.orig_invce_num,
          z.orig_invce_dte,
          z.adj_num,
          z.adj_line_num,
          z.adj_num_prior,
          z.adjitem_adjtyp_cd,
          z.submitm_num,
          z.submitem_num_prior,
          z.ar_doc_num,
          z.ar_doc_line_num,
          z.orig_ar_doc_num,
          z.orig_ar_doc_dte,
          z.x360_trans_id,
          z.x360_units_id,
          z.orig_x360_trans_id,
          z.orig_x360_trans_dte,
          z.cars_saletyp_cde,
          z.source_sys_paidto_cust_id,
          z.source_sys_mbr_id,
          z.source_billto_cust_id,
          z.source_shipto_cust_id,
          z.co_cde,
          z.bobtyp_id,
          z.perftyp_cd,
          z.demog_num,
          z.demog_qty,
          z.claim_per_start_dte,
          z.claim_per_end_dte,
          -- GPCS Fields
          z.lgcy_mod_dt,
          z.rld_new_ind,
          z.rld_reload_ind,
          z.rld_archive_ind,
          z.rld_snpsht_id,
          z.archive_ind,
          z.manual_adj_ind,
          z.man_adj_agency_cd,
          z.src_tbl_cd,
          z.trans_cls_cd,
          z.source_trans_typ,
          z.unique_id,
          z.source_sys_cde,
          z.ndc_lbl,
          z.ndc_prod,
          z.ndc_pckg,
          z.cust_id,
          z.whls_id,
          z.billto_cust_id,
          z.shipto_cust_id,
          z.trans_typ_cd,
          z.reasn_cd,
          z.invc_typ_cd,
          z.paid_dt,
          z.earn_bgn_dt,
          z.earn_end_dt,
          z.trans_dt,
          z.assc_invc_dt,
          z.claim_bgn_dt,
          z.claim_end_dt,
          z.lgcy_trans_no,
          z.lgcy_trans_line_no,
          z.assc_invc_no,
          z.assc_invc_line_no,
          z.assc_invc_source_sys_cde,
          z.contr_id,
          z.price_grp_id,
          z.related_sales_id,
          z.related_credits_id,
          z.wac_price,
          z.pkg_price,
          TO_NUMBER( SUBSTR( z.from_sales, INSTR( z.from_sales, '|', 1, 3) + 1, INSTR( z.from_sales, '|', 1, 4) - INSTR( z.from_sales, '|', 1, 3) - 1)) pkg_qty,
          TO_NUMBER( SUBSTR( z.from_sales, INSTR( z.from_sales, '|', 1, 2) + 1, INSTR( z.from_sales, '|', 1, 3) - INSTR( z.from_sales, '|', 1, 2) - 1)) claim_unit_qty,
          z.total_amt,
          z.term_disc_pct,
          z.whls_chrgbck_amt,
          TO_NUMBER( SUBSTR( z.from_sales, INSTR( z.from_sales, '|', 1, 1) + 1, INSTR( z.from_sales, '|', 1, 2) - INSTR( z.from_sales, '|', 1, 1) - 1)) gross_sale_amt,
          z.wac_extnd_amt,
          z.term_cd,
          z.actual_potency,
          z.line_ref_id,
          z.cmt_txt,
          -- Scaler subquery debugging info
          TO_NUMBER( SUBSTR( z.from_sales, INSTR( z.from_sales, '|', 1, 4) + 1, INSTR( z.from_sales, '|', 1, 5) - INSTR( z.from_sales, '|', 1, 4) - 1)) lkup_row_cnt,
          SUBSTR( z.from_sales, INSTR( z.from_sales, '|', 1, 5) + 1, INSTR( z.from_sales, '|', 1, 6) - INSTR( z.from_sales, '|', 1, 5) - 1) lkup_sales_type_cde,
          z.from_sales
     FROM ( -- Get non-chargeback credits with gross sales, packages, and units
            -- No Merge Hint prevents multiple sales subquery executions per credit row
            SELECT /*+ NO_MERGE NO_PARALLEL( iic ) DRIVING_SITE( iic ) */
                   -- ICW Fields (needed for interface queries)
                   iic.credit_num,
                   iic.created_dte,
                   iic.credit_dte,
                   iic.ndc_cde,
                   -- ICW Fields (added for support queries)
                   iic.type_cde,
                   iic.reasn_cde,
                   iic.paidto_cust_id,
                   iic.mbr_id,
                   iic.contr_ownr_id,
                   iic.contr_id_sale,
                   iic.contr_ownr_id_sale,
                   iic.cpgrp_num,
                   iic.amt,
                   iic.term_disc_pct intrpd_term_disc_pct,
                   iic.po_dte,
                   iic.invce_num,
                   iic.invce_line_num,
                   iic.orig_invce_num,
                   iic.orig_invce_dte,
                   iic.adj_num,
                   iic.adj_line_num,
                   iic.adj_num_prior,
                   iic.adjitem_adjtyp_cd,
                   iic.submitm_num,
                   iic.submitem_num_prior,
                   iic.ar_doc_num,
                   iic.ar_doc_line_num,
                   iic.orig_ar_doc_num,
                   iic.orig_ar_doc_dte,
                   iic.x360_trans_id,
                   iic.x360_units_id,
                   iic.orig_x360_trans_id,
                   iic.orig_x360_trans_dte,
                   iic.cars_saletyp_cde,
                   iic.source_sys_paidto_cust_id,
                   iic.source_sys_mbr_id,
                   iic.source_billto_cust_id,
                   iic.source_shipto_cust_id,
                   iic.co_cde,
                   iic.bobtyp_id,
                   iic.perftyp_cd,
                   iic.demog_num,
                   iic.demog_qty,
                   iic.claim_per_start_dte,
                   iic.claim_per_end_dte,
                   -- GPCS fields
                   NVL( iic.created_dte, SYSDATE) lgcy_mod_dt,
                   'Y' rld_new_ind,
                   'N' rld_reload_ind,
                   'N' rld_archive_ind,
                   TO_NUMBER( NULL) rld_snpsht_id,
                   'N' archive_ind,
                   'N' manual_adj_ind,
                   '' man_adj_agency_cd,
                   'IIC' src_tbl_cd,
                   DECODE( iic.source_sys_cde,
                           'CARS', 'R',
                           'HCRS', 'R',
                           'X360', 'R',
                           'SAP', 'D',
                           'SAP4H', 'D',
                           'BIVVRXC', 'D',
                           'BIVVCCG', 'R',
                           'BIBBMED', 'R',
                           'GNZ', 'R', -- Are all rebates? Any direct credits?
                           'XENON', 'R',
                           'SNYCARS', 'R',
                           'SNYMANUAL', 'R',
                           'SNYJDE', 'D',
                           'COSMIS', DECODE( SUBSTR( iic.type_cde, 1, 1), 'Z', 'D', 'R'), -- Some direct credits some rebates
                           'R') trans_cls_cd,
                   'C' source_trans_typ,
                   iic.credit_num unique_id,
                   iic.source_sys_cde source_sys_cde,
                   SUBSTR( iic.ndc_cde, 1, 5) ndc_lbl,
                   SUBSTR( iic.ndc_cde, 6, 4) ndc_prod,
                   SUBSTR( iic.ndc_cde, 10, 2) ndc_pckg,
                   NVL( iic.mbr_id, iic.paidto_cust_id) cust_id,
                   '' whls_id,
                   iic.billto_cust_id,
                   iic.shipto_cust_id,
                   NVL( iic.type_cde || iic.reasn_cde, 'NONE') trans_typ_cd,
                   iic.reasn_cde reasn_cd,
                   iic.type_cde invc_typ_cd,
                   iic.trans_date paid_dt,
                   NVL( iic.claim_per_start_dte, iic.trans_date) earn_bgn_dt,
                   NVL( iic.claim_per_end_dte, iic.trans_date) earn_end_dt,
                   iic.trans_date trans_dt,
                   DECODE( iic.source_sys_cde,
                           'CARS', TO_DATE( NULL, ''),
                           'HCRS', TO_DATE( NULL, ''),
                           'X360', iic.orig_ar_doc_dte,
                           'SAP', iic.orig_invce_dte,
                           'SAP4H', iic.orig_invce_dte,
                           'BIVVRXC', iic.orig_invce_dte,
                           'BIVVCCG', TO_DATE( NULL, ''),
                           'BIBBMED', TO_DATE( NULL, ''),
                           'GNZ', TO_DATE( NULL, ''),
                           'XENON', iic.orig_ar_doc_dte,
                           'SNYCARS', TO_DATE( NULL, ''),
                           'SNYMANUAL', TO_DATE( NULL, ''),
                           'SNYJDE', iic.orig_invce_dte,
                           'COSMIS', iic.orig_invce_dte,
                           TO_DATE( NULL, '')) assc_invc_dt,
                   iic.claim_per_start_dte claim_bgn_dt,
                   iic.claim_per_end_dte claim_end_dt,
                   DECODE( iic.source_sys_cde,
                           'CARS', iic.submitm_num,
                           'HCRS', iic.adj_num,
                           'X360', iic.x360_trans_id,
                           'SAP', TO_NUMBER( iic.invce_num),
                           'SAP4H', TO_NUMBER( iic.invce_num),
                           'BIVVRXC', TO_NUMBER( iic.invce_num),
                           'BIVVCCG', iic.submitm_num,
                           'BIBBMED', iic.adj_num,
                           'GNZ', TO_NUMBER( iic.invce_num),
                           'XENON', iic.ar_doc_num,
                           'SNYCARS', iic.submitm_num,
                           'SNYMANUAL', iic.submitm_num,
                           'SNYJDE', TO_NUMBER( iic.invce_num),
                           'COSMIS', iic.ar_doc_num,
                           iic.adj_num) lgcy_trans_no,
                   DECODE( iic.source_sys_cde,
                           'CARS', iic.adj_num,
                           'HCRS', iic.adj_line_num,
                           'X360', iic.x360_units_id,
                           'SAP', iic.invce_line_num,
                           'SAP4H', iic.invce_line_num,
                           'BIVVRXC', iic.invce_line_num,
                           'BIVVCCG', iic.adj_num,
                           'BIBBMED', iic.adj_line_num,
                           'GNZ', iic.invce_line_num,
                           'XENON', TO_NUMBER( NULL),
                           'SNYCARS', iic.adj_num,
                           'SNYMANUAL', iic.adj_num,
                           'SNYJDE', iic.invce_line_num,
                           'COSMIS', iic.ar_doc_line_num,
                           iic.adj_line_num) lgcy_trans_line_no,
                   DECODE( iic.source_sys_cde,
                           'CARS', iic.submitem_num_prior,
                           'HCRS', TO_NUMBER( NULL),
                           'X360', iic.orig_x360_trans_id,
                           'SAP', iic.orig_invce_num,
                           'SAP4H', iic.orig_invce_num,
                           'BIVVRXC', iic.orig_invce_num,
                           'BIVVCCG', TO_NUMBER( NULL),
                           'BIBBMED', TO_NUMBER( NULL),
                           'GNZ', TO_NUMBER( NULL),
                           'XENON', iic.orig_ar_doc_num,
                           'SNYCARS', iic.submitem_num_prior,
                           'SNYMANUAL', iic.submitem_num_prior,
                           'SNYJDE', iic.orig_invce_num,
                           'COSMIS', iic.orig_invce_num,
                           TO_NUMBER( NULL)) assc_invc_no,
                   TO_NUMBER( NULL) assc_invc_line_no,
                   CASE
                      -- SAP always uses SAP for original invoice
                      WHEN iic.source_sys_cde = 'SAP'
                       AND iic.orig_invce_num IS NOT NULL
                      THEN iic.source_sys_cde
                      -- Original source system is only populated for SAP4H invoices
                      -- SAP4H will have SAP4H or SAP for original source system
                      ELSE iic.orig_invce_src_sys_cde
                   END assc_invc_source_sys_cde,
                   iic.contr_id contr_id,
                   TO_CHAR( iic.cpgrp_num) price_grp_id,
                   iic.related_sales_num related_sales_id,
                   iic.related_credits_num related_credits_id,
                   TO_NUMBER( NULL) wac_price,
                   TO_NUMBER( NULL) pkg_price,
                   -- pkg_qty, -- see scalar subqueries below
                   -- claim_unit_qty, -- see scalar subqueries below
                   NVL( iic.amt, 0) * -1 total_amt,
                   CASE
                      WHEN iic.source_sys_cde IN ('SAP', 'SAP4H', 'BIVVRXC')
                      THEN NVL( iic.term_disc_pct, 0)
                      ELSE TO_NUMBER( NULL)
                   END term_disc_pct,
                   TO_NUMBER( NULL) whls_chrgbck_amt,
                   -- gross_sale_amt, -- see scalar subqueries below
                   TO_NUMBER( NULL) wac_extnd_amt,
                   iic.terms term_cd,
                   TO_NUMBER( NULL) actual_potency,
                   '' line_ref_id,
                   '' cmt_txt,
                   -- Gross Dollars/Claim Units/Pkg Units from sales
                   -- Returns pipe delimited string of:
                   -- gross_sale_amt | claim_unit_qty | pkg_qty | lkup_row_cnt | lkup_sales_type_cde
                   SUBSTR(
                   CASE
                      -- ICW_KEY rebates/fees, non-product rebates/fees, Coverage gap
                      WHEN iic.related_sales_num IS NOT NULL
                        OR iic.related_credits_num IS NOT NULL
                        OR iic.ndc_cde IS NULL
                        OR iic.ndc_cde LIKE '%000000'
                      THEN '|0|0|0|0||'
                      -- RMUS/CARS transactions
                      -- BIVVCCG - Legacy Bioverativ CCG FLEX transactions
                      -- SNYCARS - Legacy Sanofi CARS transactions
                      -- SNYMANUAL - Legacy Sanofi CARS Manual transactions
                      WHEN iic.source_sys_cde IN ('CARS', 'BIVVCCG', 'SNYCARS', 'SNYMANUAL')
                      THEN (
                              -- CARS/SNYCARS/SNYMANUAL credits can be linked to either a UTIL, CUSTSLS or INDIRECT sales record
                              -- BIVVCCG credits can be linked to a UTIL sales record (there are no CUSTSLS or INDIRECT)
                              -- UTIL uses claim_units so set pkg_qty to zero
                              -- CUSTSLS and INDIRECT uses pkg_units so set claim_units to NULL
                              -- No Parallel hint makes ICW use the correct index on submitm_num, adj_num
                              SELECT /*+ NO_PARALLEL( iis ) */
                                     '|' ||
                                     TO_CHAR( NVL( SUM( iis.gross_sale_amt + NVL( iis.chrgbk_claim_amt, 0)), 0)) || '|' ||
                                     TO_CHAR( NVL( SUM( DECODE( iis.sales_type_cde, 'UTIL', iis.claim_units)), 0)) || '|' ||
                                     TO_CHAR( NVL( SUM( DECODE( iis.sales_type_cde, 'UTIL', 0, iis.pkg_units)), 0)) || '|' ||
                                     COUNT(*) || '|' ||
                                     MIN( iis.sales_type_cde) || '|'
                                FROM hcrs.icw2_intrpd_sales_v iis
                               WHERE iis.sale_dte BETWEEN iic.claim_per_start_dte AND iic.claim_per_end_dte  -- partition elimination
                                 AND iis.source_sys_cde = iic.source_sys_cde
                                 AND iis.cust_id = NVL( iic.mbr_id, iic.paidto_cust_id)
                                 AND iis.ndc_cde = iic.ndc_cde
                                 AND iis.submitm_num = iic.submitm_num
                                 AND (   (    iis.sales_type_cde IN ('UTIL', 'CUSTSLS')
                                          AND iis.claim_per_start_dte = iic.claim_per_start_dte
                                          AND iis.claim_per_end_dte = iic.claim_per_end_dte
                                          AND iis.adj_num = iic.adj_num
                                         )
                                      OR (    iis.sales_type_cde = 'INDIRECT'
                                          AND iis.whlslr_invce_dte BETWEEN iic.claim_per_start_dte AND iic.claim_per_end_dte
                                          AND iis.created_dte <= iic.created_dte
                                          AND iis.chrgbk_claim_amt IS NOT NULL
                                         )
                                     )
                           )
                      -- HCRS transactions
                      -- BIBBMED - Biogen Medicaid transactions
                      WHEN iic.source_sys_cde IN ('HCRS', 'BIBBMED')
                      THEN (
                              -- HCRS/BIBBMED credits can be linked to a MEDUTIL sales record
                              -- No Parallel hint makes ICW use the correct index on adj_num
                              SELECT /*+ NO_PARALLEL( iis ) */
                                     '|' ||
                                     TO_CHAR( NVL( SUM( iis.gross_sale_amt), 0)) || '|' ||
                                     TO_CHAR( NVL( SUM( iis.claim_units), 0)) || '|' ||
                                     '0|' ||
                                     COUNT(*) || '|' ||
                                     MIN( iis.sales_type_cde) || '|'
                                FROM hcrs.icw2_intrpd_sales_v iis
                               WHERE iis.sale_dte = iic.credit_dte -- partition elimination
                                 AND iis.source_sys_cde = iic.source_sys_cde
                                 AND iis.claim_per_start_dte = iic.claim_per_start_dte
                                 AND iis.claim_per_end_dte = iic.claim_per_end_dte
                                 AND iis.cust_id = iic.paidto_cust_id
                                 AND iis.ndc_cde = iic.ndc_cde
                                 AND iis.sales_type_cde = 'MEDUTIL'
                                 AND iis.adj_num = iic.adj_num
                                 -- HCRS/BIBBMED records come singly or in pairs
                                 -- sign of MEDUTIL gross_sale_amt always matches sign of credit amt
                                 AND SIGN( iis.gross_sale_amt) = SIGN( iic.amt)
                           )
                      -- X360 transactions (New Xenon Process)
                      WHEN iic.source_sys_cde = 'X360'
                      THEN (
                              -- X360 credits can be linked to a DPA2 sales record
                              SELECT /*+ NO_PARALLEL( iis ) */
                                     '|' ||
                                     TO_CHAR( NVL( SUM( iis.gross_sale_amt), 0)) || '|' ||
                                     '0|' ||
                                     TO_CHAR( NVL( SUM( iis.pkg_units), 0)) || '|' ||
                                     COUNT(*) || '|' ||
                                     MIN( iis.sales_type_cde) || '|'
                                FROM hcrs.icw2_intrpd_sales_v iis
                               WHERE iis.sale_dte = iic.credit_dte -- partition elimination
                                 AND iis.source_sys_cde = iic.source_sys_cde
                                 AND iis.claim_per_start_dte = iic.claim_per_start_dte
                                 AND iis.claim_per_end_dte = iic.claim_per_end_dte
                                 AND iis.cust_id = NVL( iic.mbr_id, iic.paidto_cust_id)
                                 AND iis.ndc_cde = iic.ndc_cde
                                 AND iis.sales_type_cde = 'DPA2'
                                 AND iis.x360_trans_id = iic.x360_trans_id
                                 AND iis.x360_units_id = iic.x360_units_id
                           )
                      -- COSMIS rebate transactions
                      -- No sales lookup, set to gross sales, claim units, and packages to zero
                      WHEN iic.source_sys_cde = 'COSMIS'
                       AND iic.type_cde NOT LIKE 'Z%'
                      THEN '|0|0|0|0||'
                      -- SAP direct credit transactions
                      -- SAP4H direct credit transactions
                      -- BIVVRXC - Legacy Bioverativ RxCrossroads direct credit transactions
                      -- GNZ - Legacy Genzyme direct credit transactions
                      -- SNYJDE - Legacy Sanofi JDE direct credit transactions
                      -- COSMIS direct credit transactions
                      -- No sales lookup, set to gross sales and claim units to null, packages to zero
                      WHEN iic.source_sys_cde IN ('SAP', 'SAP4H', 'BIVVRXC', 'GNZ','SNYJDE', 'COSMIS')
                      THEN '|||0|0||'
                      -- XENON transactions (archived and discontinued)
                      WHEN iic.source_sys_cde = 'XENON'
                      THEN (
                              -- XENON credits can be linked to a DPA sales record
                              SELECT /*+ NO_PARALLEL( iis ) */
                                     '|' ||
                                     TO_CHAR( NVL( SUM( iis.gross_sale_amt), 0)) || '|' ||
                                     '0|' ||
                                     TO_CHAR( NVL( SUM( iis.pkg_units), 0)) || '|' ||
                                     COUNT(*) || '|' ||
                                     MIN( iis.sales_type_cde) || '|'
                                FROM hcrs.icw2_intrpd_sales_v iis
                               WHERE iis.sale_dte = iic.credit_dte -- partition elimination
                                 AND iis.source_sys_cde = iic.source_sys_cde
                                 AND iis.claim_per_start_dte = iic.claim_per_start_dte
                                 AND iis.claim_per_end_dte = iic.claim_per_end_dte
                                 AND iis.cust_id = NVL( iic.mbr_id, iic.paidto_cust_id)
                                 AND iis.ndc_cde = iic.ndc_cde
                                 AND iis.sales_type_cde = 'DPA'
                                 AND iis.ar_doc_num = iic.ar_doc_num
                           )
                      -- All other transaction types (ICON & Manual)
                      ELSE (
                              -- All other credits can be linked to a UTIL sales record
                              -- No Parallel hint makes ICW use the correct index on adj_num
                              SELECT /*+ NO_PARALLEL( iis ) */
                                     '|' ||
                                     TO_CHAR( NVL( SUM( iis.gross_sale_amt), 0)) || '|' ||
                                     TO_CHAR( NVL( SUM( iis.claim_units), 0)) || '|' ||
                                     '0|' ||
                                     COUNT(*) || '|' ||
                                     MIN( iis.sales_type_cde) || '|'
                                FROM hcrs.icw2_intrpd_sales_v iis
                               WHERE iis.sale_dte = iic.credit_dte -- partition elimination
                                 AND iis.source_sys_cde = iic.source_sys_cde
                                 AND iis.claim_per_start_dte = iic.claim_per_start_dte
                                 AND iis.claim_per_end_dte = iic.claim_per_end_dte
                                 AND iis.cust_id = NVL( iic.mbr_id, iic.paidto_cust_id)
                                 AND iis.ndc_cde = iic.ndc_cde
                                 AND iis.contr_id = iic.contr_id
                                 AND iis.sales_type_cde = 'UTIL'
                                 AND iis.adj_num = iic.adj_num
                           )
                   END, 1, 100) from_sales
              FROM hcrs.icw2_intrpd_credits_v iic
                -- Eliminate non-US companys (easier to delete extra data for new companies)
             WHERE iic.co_cde NOT IN ('------',
                                      --'0901', -- Sanofi US Services Inc.
                                      --'1209', -- Sanofi US Corporation
                                      --'2039', -- sanofi-aventis U.S. LLC
                                      --'2100', -- Merrell Pharma Inc.
                                      '2106',   -- Aventis Pharma, Inc (PR)
                                      --'2123', -- Blue Ridge Laboratories
                                      --'5100', -- Genzyme Corporation
                                      --'9338', -- Sanofi-Synthelabo Inc
                                      'PR02', -- Sanofi PR
                                      --'US03', -- Genzyme Corporation US
                                      --'US12', -- Bioverativ US
                                      '------')
                -- No chargeback credits
               AND iic.type_cde <> 'CAC'
                -- Block Genzyme manual data for SPM source/sales code
               AND iic.source_sys_cde NOT IN ('GNZMANRBT')
          ) z;
