CREATE OR REPLACE VIEW product AS
SELECT mv.product_id,
       mv.brand_name,
       mv.ndc9,
       mv.ndc11,
       mv.description,
       mv.fda_registered_name AS Secondary_Description,
       mv.product_type,
       mv.product_strength,
       mv.units_of_measure,
       mv.units_per_package_size,
       mv.package_size,
       mv.desi_indicator AS DESI_Code,
       mv.medicaid_category AS Drug_Category,
       mv.fda_approval_date,
       mv.market_date_ndc9,
       mv.market_date_ndc11,
       mv.first_sale_date_ndc9,
       mv.first_sale_date_ndc11,
       mv.termination_date_ndc9,
       mv.termination_date_ndc11,
       mv.last_lot_mfr_date_ndc9,
       mv.last_lot_mfr_date_ndc11,
       mv.last_sale_date_ndc9,
       mv.last_sale_date_ndc11,
       mv.last_lot_expiration_date_ndc9,
       mv.last_lot_expiration_date_ndc11,
       mv.status,
       mv.product_id_type,
       mv.product_source,
       mv.external_key,
       mv.purchase_date,
       mv.va_stop_report_date,
       mv.va_first_sale_date,
       mv.divestiture_date,
       mv.description_ndc9,
       mv.trade_name,
       mv.otc_flag AS Drug_Type,
       mv.vaccine_flag,
       mv.fda_thera_eq_code,
       mv.baseline_amp,
       mv.baseline_amp_dra,
       mv.drug_category_eff_date,
       mv.cms_last_mod_date,
       mv.cms_stop_report_date,
       mv.dosage_form,
       mv.sin,
       mv.integration_id,
       to_date('01/01/1984', 'MM/DD/YYYY') AS rec$_effective_start_date,
       to_date('12/31/2099', 'MM/DD/YYYY') AS rec$_effective_end_date,
       -- TODO: change production date and obsolete date as well
       to_date('01/01/1984', 'MM/DD/YYYY') AS rec$_production_date,
       CAST(NULL AS DATE) AS rec$_obsolete_date,
       mv.ndc11 AS rec$_record_key,
       mv.last_update_date,
       mv.units_per_package_size AS units_per_pack,
       mv.dosage_form AS dosage,
       mv.status_ndc9,
       mv.external_key_ndc9,
       mv.cms_last_mod_date_ndc9,
       mv.prod_dt_added_in_cars,
     mv.va_product_add_mod_date AS va_product_add_mod_date,
     mv.va_prod_add_mod_number AS va_prod_add_mod_number,
     mv.fda_approval_type AS fda_approval_type,
     mv.fda_application_number AS fda_application_number,
     mv.cms_amp_category AS cms_amp_category,
     mv.generic_name AS generic_name,
     mv.inner_pack_indicator AS inner_pack_indicator,
     mv.use_reduced_percent AS use_reduced_percent,
     mv.market_entry_date_ndc9 AS CMS_Market_Date,
     mv.cms_stop_report_date_ndc11 AS CMS_Expiration_Date,
     mv.manufacturer AS manufacturer,
     CAST(mv.prod_size_cnv AS NUMBER) AS prod_size_cnv,
     mv.medi_units_per_pkg AS medi_units_per_pkg,
     mv.intro_date AS intro_date,
     mv.asp_last_mod_date AS asp_last_mod_date,
     mv.fda_approval_number AS fda_approval_number,
    mv.unit_type AS unit_type,
     mv.alternate_product_id,
     mv.volume_per_item,
     mv.fda_application_suppl_number,
     mv.addl_fda_application_number_1,
     mv.addl_fda_application_suppl_1,
     mv.addl_fda_application_number_2,
     mv.addl_fda_application_suppl_2,
     mv.other_approval_type_descr,
     mv.prod_num_ndc9,
     mv.indicator_5i AS indicator_5i,
     mv.threshold_5i AS threshold_5i,
     mv.route_5i AS route_5i,
     mv.medicaid_cod AS medicaid_cod,
     mv.ddr_fda_application_number AS ddr_fda_application_number,
    mv.line_extension_drug_indicator AS line_extension_drug_indicator,
     mv.baseline_amp_aca AS baseline_amp_aca,
    mv.global_flag AS global_flag
FROM mdm_prod_vw mv
;
