set feedback off
set define off

prompt Truncating BIVV.MEDI_PGMS_MAP_BIOGEN_T...
truncate table BIVV.MEDI_PGMS_MAP_BIOGEN_T;
prompt Loading BIVV.MEDI_PGMS_MAP_BIOGEN_T...
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('AK', 'ALASKA', 'MEDI', '43000_Medicaid', 4, 1, 'ALASKA FDRL', 'ALASKA FEDERAL MEDICAID', 2, 'FEDERAL', 'FDRL', '2018Q3', '2018Q4', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('AL', 'ALABAMA', 'MEDI', '43000_Medicaid', 4, 2, 'ALABAMA FDRL', 'ALABAMA FEDERAL MEDICAID ', 127, 'FEDERAL', 'FDRL', '2014Q3', '2019Q2', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('AR', 'ARKANSAS', 'MEDI', '43000_Medicaid', 4, 3, 'ARKANSAS FDRL', 'ARKANSAS FEDERAL MEDICAID', 70, 'FEDERAL', 'FDRL', '2014Q2', '2019Q1', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('AR', 'ARKANSAS', 'Medi_Exp', '43000_Medicaid Expansion', 72060, 1660, 'ARKANSAS FFS EXPAN', 'ARKANSAS FEDERAL MEDICAID EXPANSION', 24, 'FEDERAL', null, '2015Q1', '2018Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('AR', 'ARKANSAS', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1797, 'ARKANSAS PASSE PH ENC', 'ARKANSAS PASSE PHARMACY ENCOUNTER PROGRAM', 3, 'MMCO', null, '2019Q1', '2019Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('AZ', 'ARIZONA', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1543, 'ARIZONA MMC', 'ARIZONA MEDICAID MANAGED CARE', 31, 'MMCO', null, '2016Q2', '2019Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('CA', 'CALIFORNIA', 'CA_Blood_Factors', '43000_CA Blood Factors', 78060, 263, 'CALIFORNIA  BLOOD', 'CALIFORNIA BLOOD FACTOR', 418, 'FEDERAL', null, '2014Q3', '2020Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('CA', 'CALIFORNIA', 'CA_BF_ACA', '43000_CA Blood Factors ACA', 138060, 1818, 'CA BLOOD FACTORS ACA', 'CALIFORNIA BLOOD FACTORS ACA', 197, 'FEDERAL', null, '2016Q2', '2019Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('CA', 'CALIFORNIA', 'CA GHPP', '43000_CA GHPP', 76061, 1806, 'CA GENETICALLY HANDICA', 'CALIFORNIA GENETICALLY HANDICAPPED PERSONS PROG', 401, 'FEDERAL', null, '2014Q2', '2020Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('CA', 'CALIFORNIA', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1600, 'CALIFORNIA  MMC', 'CALIFORNIA MEDICAID MANAGED CARE', 1, 'MMCO', null, '2019Q2', '2019Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('CA', 'CALIFORNIA', 'CA_BloodFctrSUPP', '43002_CA Blood Factors SUPP', 94060, 1817, 'CA BLOOD FACTOR SUPP', 'CALIFORNIA BLOOD FACTORS SUPP', 2249, 'SUPPLEMENT', null, '2014Q3', '2020Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('CA', 'CALIFORNIA', 'CA GHPP SPAP', '43002_CA GHPP SUPP', 76062, 1813, 'CA GEN HAND HCPCS SUPP', 'CALIFORNIA GENETICALLY HANDICAPPED PERSONS PROG HCPCS SUPP', 78, 'SUPPLEMENT', null, '2014Q2', '2015Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('CA', 'CALIFORNIA', 'CA GHPP SUPP', '43002_CA GHPP Supplemental', 108060, 1808, 'CA GEN HAND PERS SUPP', 'CALIFORNIA GENETICALLY HANDICAPPED PERSONS PROG SUPP', 1861, 'SUPPLEMENT', null, '2014Q2', '2020Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('CA', 'CALIFORNIA', 'CABFSUPPACA', '43002_CA_BloodFct_SUPP_ACA', 137061, 1819, 'CA BF ACA SUPP', 'CALIFORNIA BLOOD FACTORS ACA SUPP', 478, 'SUPPLEMENT', null, '2016Q2', '2019Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('CA', 'CALIFORNIA', 'CA GHPP', '43003_CA GHPP_SPAP', 76061, 1807, 'CA GEN HAND HCPCS', 'CALIFORNIA GENETICALLY HANDICAPPED PERSONS HCPCS', 19, 'SPAP', null, '2014Q2', '2014Q4', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('CO', 'COLORADO', 'FSS EXP CHIP', '43000_FSS EXP CHIP', 154060, 1742, 'COLORADO FDRL CHIP', 'COLORADO MEDICAID CHIP PROGRAM', 10, 'MMCO', null, '2018Q1', '2018Q4', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('CO', 'COLORADO', 'MEDI', '43000_Medicaid', 4, 5, 'COLORADO FDRL', 'COLORADO FEDERAL MEDICAID ', 65, 'FEDERAL', 'FDRL', '2015Q4', '2019Q1', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('CO', 'COLORADO', 'Medi_Exp', '43000_Medicaid Expansion', 72060, 1735, 'COLORADO FEDERAL EXP', 'COLORADO MEDICAID EXPANSION', 30, 'FEDERAL', null, '2017Q2', '2019Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('CT', 'CONNECTICUT', 'CT - LIA', '43000_CT Medi Low Income Adult', 38, 1532, 'CONNECTICUT MLIA', 'CONNECTICUT MEDICAID LOW INCOME ADULTS', 36, 'FEDERAL', null, '2016Q3', '2019Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('CT', 'CONNECTICUT', 'MEDI', '43000_Medicaid', 4, 6, 'CONNECTICUT FDRL', 'CONNECTICUT FEDERAL MEDICAID ', 44, 'FEDERAL', 'FDRL', '2016Q3', '2020Q1', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('DC', 'DISTRICT OF COLUMBIA', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1572, 'DC MMC', 'DISTRICT OF COLUMBIA MEDICAID MANAGED CARE', 76, 'MMCO', null, '2014Q4', '2018Q4', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('DC', 'DISTRICT OF COLUMBIA', 'MCO-EXP CHIP', '43001_MCO EXP CHIP', 147060, 1702, 'DC CHIP MMC', 'DC CHIP MANAGED CARE', 1, 'MMCO', null, '2018Q4', '2018Q4', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('DE', 'DELAWARE', 'MEDI', '43000_Medicaid', 4, 8, 'DELAWARE FDRL', 'DELAWARE FEDERAL MEDICAID ', 67, 'FEDERAL', 'FDRL', '2014Q3', '2018Q4', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('DE', 'DELAWARE', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1584, 'DELAWARE MMC', 'DELAWARE MEDICAID MANAGED CARE', 140, 'MMCO', null, '2015Q1', '2020Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('FL', 'FLORIDA', 'FFS_SS_MED', '43000_FFS Single-Source Med', 83060, 409, 'FLORIDA FDRL-J', 'FLORIDA FEDERAL MEDICAID -J CODES', 23, 'FEDERAL', null, '2016Q2', '2019Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('FL', 'FLORIDA', 'MEDI', '43000_Medicaid', 4, 9, 'FLORIDA FDRL', 'FLORIDA FEDERAL MEDICAID ', 416, 'FEDERAL', 'FDRL', '2014Q2', '2019Q3', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('FL', 'FLORIDA', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1596, 'FLORIDA MMC', 'FLORIDA MEDICAID MANAGED CARE (MCO)', 5, 'MMCO', null, '2017Q3', '2018Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('FL', 'FLORIDA', 'MCO_FED_MED', '43001_MCO Federal Medical', 83061, 1610, 'FLORIDA MMC J CODE', 'FLORIDA MEDICAID MANAGED CARE J-CODE', 3, 'MMCO', null, '2018Q2', '2018Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('GA', 'GEORGIA', 'MEDI', '43000_Medicaid', 4, 10, 'GEORGIA FDRL', 'GEORGIA FEDERAL MEDICAID', 111, 'FEDERAL', 'FDRL', '2014Q2', '2019Q4', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('GA', 'GEORGIA', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1545, 'GA AMERIGROUP MCO', 'GEORGIA MEDICAID MANAGED CARE (AMERIGROUP)', 59, 'MMCO', null, '2014Q4', '2018Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('GA', 'GEORGIA', 'HCPCS-MCO', '43001_JCODE - MCO', 23060, 1783, 'GA WELLCARE MCO MED', 'GEORGIA WELLCARE OF GA MCO MEDICAL', 57, 'MMCO', null, '2015Q1', '2018Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('GA', 'GEORGIA', 'MCO-WELLCARE', '43001_MCO - Wellcare', 76064, 1784, 'GA WELLCARE MCO', 'GEORGIA WELLCARE OF GA MCO', 10, 'MMCO', null, '2018Q3', '2019Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('GA', 'GEORGIA', 'MCO-Peach', '43001_MCO-Peach', 159060, 1782, 'GA PEACH MCO', 'GEORGIA PEACH STATE HEALTH PLAN MCO', 3, 'MMCO', null, '2018Q2', '2018Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('GA', 'GEORGIA', 'MCO_HCPCS_Ameri', '43001_MCO_HCPCS_Amerigroup', 157060, 1555, 'GA AMERIGROUP MCO MED', 'GEORGIA MEDICAID MANAGED CARE J-CODES (AMERIGROUP)', 33, 'MMCO', null, '2018Q2', '2018Q4', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('GA', 'GEORGIA', 'MCO_HCPCS_Caresou', '43001_MCO_HCPCS_Caresource', 157061, 1778, 'GA CARESOURCE MCO MED', 'GEORGIA CARESOURCE MCO MEDICAL', 33, 'MMCO', null, '2018Q2', '2019Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('GA', 'GEORGIA', 'MCO-HCPCS-Peach', '43001_MCO_HCPCS_Peach', 158061, 1781, 'GA PEACH MCO MED', 'GEORGIA PEACH STATE HEALTH PLAN MCO MEDICAL', 2, 'MMCO', null, '2018Q2', '2018Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('HI', 'Hawaii', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1578, 'HAWAII MMC', 'HAWAII MEDICAID MANAGED CARE', 79, 'MMCO', null, '2015Q2', '2019Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('IA', 'Iowa', 'HCPCS', '43000_JCODE - Medicaid', 17, 412, 'IOWA FDRL-J (3000)', 'IOWA FEDERAL MEDICAID -J CODES (3000)', 1, 'FEDERAL', null, '2016Q2', '2016Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('IA', 'Iowa', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1690, 'IOWA MMC 1500', 'IOWA MMC 1500', 41, 'MMCO', null, '2016Q4', '2019Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('IA', 'Iowa', 'HCPCS-MCO', '43001_JCODE - MCO', 23060, 1624, 'IOWA MMC JCODE 3500', 'IOWA MEDICAID MANAGED CARE J-CODES (3500)', 2, 'MMCO', null, '2017Q1', '2019Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('ID', 'Idaho', 'MEDI', '43000_Medicaid', 4, 13, 'IDAHO FDRL', 'IDAHO FEDERAL MEDICAID ', 89, 'FEDERAL', 'FDRL', '2014Q3', '2018Q4', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('IL', 'Illinois', 'HCPCS', '43000_JCODE - Medicaid', 17, 414, 'ILLINOIS FDRL-J', 'ILLINOIS FEDERAL MEDICAID-J CODES', 29, 'FEDERAL', null, '2015Q2', '2018Q4', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('IL', 'Illinois', 'MEDI', '43000_Medicaid', 4, 14, 'ILLINOIS FDRL', 'ILLINOIS FEDERAL MEDICAID', 94, 'FEDERAL', 'FDRL', '2014Q3', '2019Q3', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('IL', 'Illinois', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1594, 'ILLINOIS MMC', 'ILLINOIS MEDICAID MANAGED CARE', 96, 'MMCO', null, '2014Q3', '2019Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('IL', 'Illinois', 'HCPCS-MCO', '43001_JCODE - MCO', 23060, 1595, 'ILLINOIS MMC J-CODE', 'ILLINOIS MEDICAID MANAGED CARE J-CODE', 1, 'MMCO', null, '2018Q2', '2018Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('IN', 'Indiana', 'MEDI', '43000_Medicaid', 4, 15, 'INDIANA FDRL', 'INDIANA FEDERAL MEDICAID ', 528, 'FEDERAL', 'FDRL', '2014Q3', '2020Q1', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('IN', 'Indiana', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1581, 'INDIANA MMC', 'INDIANA MEDICAID MANAGED CARE', 274, 'MMCO', null, '2015Q2', '2018Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('KS', 'Kansas', 'MEDI', '43000_Medicaid', 4, 16, 'KANSAS FDRL', 'KANSAS FEDERAL MEDICAID ', 2, 'FEDERAL', 'FDRL', '2017Q4', '2018Q1', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('KS', 'Kansas', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1593, 'KANSAS MMC', 'KANSAS MEDICAID MANAGED CARE PROGRAM', 88, 'MMCO', null, '2014Q4', '2019Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('KY', 'Kentucky', 'MEDI', '43000_Medicaid', 4, 17, 'KENTUCKY FDRL KYH', 'KENTUCKY FEDERAL MEDICAID (KYH)', 67, 'FEDERAL', null, '2014Q4', '2019Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('KY', 'Kentucky', 'KYCOVENTRY', '43001 MCO - KY Coventry', 58, 1574, 'KENTUCKY MMC COVENTR', 'KENTUCKY MMC COVENTRY CARES (K02)', 109, 'MMCO', null, '2015Q4', '2020Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('KY', 'Kentucky', 'KYHUMANA', '43001 MCO - KY Humana', 11060, 1607, 'KENTUCKY MMC HUMANA', 'KENTUCKY MMC HUMANA ( K05)', 4, 'MMCO', null, '2015Q4', '2017Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('KY', 'Kentucky', 'KYANTHEM', '43001 MCO-KY Anthem', 74061, 1631, 'KENTUCKY MMC ANTHEM ', 'KENTUCKY MMC ANTHEM (K06)', 21, 'MMCO', null, '2017Q2', '2019Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('KY', 'Kentucky', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1540, 'KENTUCKY MMC KYO', 'KENTUCKY MEDICAID MANAGED CARE (KYO)', 28, 'MMCO', null, '2015Q1', '2019Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('KY', 'Kentucky', 'MCO-WELLCARE', '43001_MCO - Wellcare', 76064, 1576, 'KENTUCKY MMC WELLCAR', 'KENTUCKY MEDICAID MANAGED CARE WELLCARE (K04)', 90, 'MMCO', null, '2014Q3', '2019Q4', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('KY', 'Kentucky', 'MCO MediEXP', '43001_MCO MediEXP', 77061, 1665, 'KENTUCY MMC  EXP', 'KENTUCKY  MEDICAID MANAGED CARE MCO EXPANSION', 19, 'MMCO', null, '2017Q3', '2019Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('LA', 'Louisiana', 'HCPCS', '43000_JCODE - Medicaid', 17, 418, 'LOUISIANA FDRL-J', 'LOUISIANA FEDERAL MEDICAID -J CODES', 49, 'FEDERAL', null, '2016Q3', '2019Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('LA', 'Louisiana', 'MEDI', '43000_Medicaid', 4, 18, 'LOUISIANA FDRL', 'LOUISIANA FEDERAL MEDICAID', 49, 'FEDERAL', 'FDRL', '2014Q3', '2018Q4', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('LA', 'Louisiana', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1605, 'LOUISIANA MMC', 'LOUISIANA MEDICAID MANAGED CARE', 163, 'MMCO', null, '2015Q1', '2019Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('LA', 'Louisiana', 'HCPCS-MCO', '43001_JCODE - MCO', 23060, 1604, 'LA MMC JCODE CROSS', 'LOUISIANA MEDICAID MANAGED CARE J-CODE AND CROSSOVER', 86, 'MMCO', null, '2015Q4', '2020Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('LA', 'Louisiana', 'MCO MediEXP', '43001_MCO MediEXP', 77061, 1694, 'LOUISIANA MMC EXP', 'LOUISIANA MEDICAID MANAGED CARE EXPANSION', 10, 'MMCO', null, '2017Q4', '2018Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MA', 'Massachusetts', 'MEDI', '43000_Medicaid', 4, 19, 'MASSACHUSETTS FDRL', 'MASSACHUSETTS FEDERAL MEDICAID ', 44, 'FEDERAL', 'FDRL', '2014Q3', '2019Q1', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MA', 'Massachusetts', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1534, 'MASSACHUSETTS MMC', 'MASSACHUSETTS MEDICAID MANAGED CARE', 17, 'MMCO', null, '2014Q4', '2019Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MD', 'Maryland', 'MD CHP', '43000_MD CHP', 91060, 1648, 'MARYLAND EXPMCHP FFS', 'MARYLAND EXP CHILDRENS HEALTH  PROGRAM FFS', 53, 'FEDERAL', null, '2015Q1', '2019Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MD', 'Maryland', 'MEDI', '43000_Medicaid', 4, 20, 'MARYLAND FDRL', 'MARYLAND FEDERAL MEDICAID ', 49, 'FEDERAL', 'FDRL', '2014Q4', '2019Q2', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MD', 'Maryland', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1541, 'MARYLAND MMC', 'MARYLAND MEDICAID MANAGED CARE', 2, 'MMCO', null, '2017Q2', '2019Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MD', 'Maryland', 'MCO_MD_ACA', '43001_MCO_Maryland_ACA', 78062, 1645, 'MARYLAND EXP NA MCO', 'MARYLAND MEDICAID EXPANSION NEW ADULTS MCO', 2, 'MMCO', null, '2017Q3', '2017Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('ME', 'Maine', 'HCPCS', '43000_JCODE - Medicaid', 17, 421, 'MAINE FDRL-J', 'MAINE FEDERAL MEDICAID -J CODES', 30, 'FEDERAL', null, '2017Q2', '2019Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('ME', 'Maine', 'JCODEMEDICAL', '43000_JCODE_Medical', 142060, 1515, 'MAINE HOSPITAL J-COD', 'MAINE HOSPITAL J-CODE', 18, 'FEDERAL', null, '2017Q2', '2020Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('ME', 'Maine', 'MEDI', '43000_Medicaid', 4, 21, 'MAINE FDRL', 'MAINE FEDERAL MEDICAID', 48, 'FEDERAL', 'FDRL', '2016Q1', '2018Q4', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MI', 'Michigan', 'MEDI', '43000_Medicaid', 4, 22, 'MICHIGAN FDRL', 'MICHIGAN FEDERAL MEDICAID', 330, 'FEDERAL', 'FDRL', '2014Q2', '2019Q2', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MI', 'Michigan', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1539, 'MICHIGAN MMC', 'MICHIGAN MEDICAID MANAGED CARE', 25, 'MMCO', null, '2017Q2', '2019Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MI', null, null, null, null, 928, 'MICHIGAN ADAP', 'MICHIGAN ADAP', null, null, 'MIADAP', null, null, to_date('01-10-2005', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MI', null, null, null, null, 888, 'MICHIGAN EPIC', 'MICHIGAN EPIC', null, null, 'MI EPIC', null, null, to_date('01-07-2004', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MI', null, null, null, null, 22, 'MICHIGAN FDRL', 'MICHIGAN FEDERAL MEDICAID', null, null, 'FDRL', null, null, to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MI', null, null, null, null, 422, 'MICHIGAN FDRL-J', 'MICHIGAN FEDERAL MEDICAID -J CODES', null, null, 'FDRL-J', null, null, to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MI', null, null, null, null, 1539, 'MICHIGAN MMC', 'MICHIGAN MEDICAID MANAGED CARE', null, null, 'MI MMC', null, null, to_date('01-01-2010', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MI', null, null, null, null, 703, 'MICHIGAN SUPP', 'MICHIGAN SUPPLEMENTAL', null, null, 'MIPDL', null, null, to_date('01-07-2004', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MN', 'Minnesota', 'MEDI', '43000_Medicaid', 4, 23, 'MINNESOTA FDRL', 'MINNESOTA FEDERAL MEDICAID', 73, 'FEDERAL', 'FDRL', '2014Q4', '2019Q2', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MN', 'Minnesota', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1559, 'MINNESOTA MMC', 'MINNESOTA MEDICAID MANAGED CARE', 13, 'MMCO', null, '2015Q2', '2019Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MN', 'Minnesota', 'MCO MediEXP', '43001_MCO MediEXP', 77061, 1654, 'MINNESOTA MMC  EXP', 'MINNESOTA  MEDICAID MANAGED CARE MCO EXPANSION', 6, 'MMCO', null, '2017Q2', '2018Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MO', 'Missouri', 'MEDI', '43000_Medicaid', 4, 24, 'MISSOURI FDRL', 'MISSOURI FEDERAL MEDICAID ', 346, 'FEDERAL', 'FDRL', '2014Q3', '2020Q1', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MS', 'Mississippi', 'MEDI', '43000_Medicaid', 4, 25, 'MISSISSIPPI FDRL', 'MISSISSIPPI FEDERAL MEDICAID ', 137, 'FEDERAL', 'FDRL', '2014Q4', '2019Q2', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MT', 'Montana', 'MEDI', '43000_Medicaid', 4, 26, 'MONTANA FDRL', 'MONTANA FEDERAL MEDICAID ', 2, 'FEDERAL', 'FDRL', '2017Q3', '2017Q3', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('MT', 'Montana', 'Medi_Exp', '43000_Medicaid Expansion', 72060, 1669, 'MONTANA FFS EXP HELP', 'MONTANA FEDERAL MEDICAID EXPANSION HELP', 19, 'FEDERAL', null, '2017Q4', '2018Q4', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('NC', 'North Carolina', 'MEDI', '43000_Medicaid', 4, 27, 'NORTH CAROLINA FDRL', 'NORTH CAROLINA FEDERAL MEDICAID ', 351, 'FEDERAL', 'FDRL', '2014Q4', '2019Q3', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('ND', 'North Dakota', 'HCPCS-MCO MediExp', '43001_JCODE - MCO MediExp', 85062, 1644, 'NORTH DAKOT EXP MMCJ', 'NORTH DAKOTA EXPANSION MMC J CODE', 8, 'MMCO', null, '2017Q2', '2017Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('NE', 'Nebraska', 'MEDI', '43000_Medicaid', 4, 29, 'NEBRASKA FDRL', 'NEBRASKA FEDERAL MEDICAID ', 22, 'FEDERAL', 'FDRL', '2015Q3', '2017Q4', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('NE', 'Nebraska', 'MCO_NE 7300', '43001_NE Total Care 7300 MCOP0', 146062, 1727, 'NEBRASKA MMC (7300)', 'NEBRASKA MEDICAID MANAGED CARE (7300)', 19, 'MMCO', null, '2017Q2', '2018Q4', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('NE', 'Nebraska', 'HCPCS-NE MCO 7100', '43001_NE United 7100 MCO HCPCS', 146063, 1723, 'NE MMC J-CODE (7100)', 'NEBRASKA MMC J CODE (7100) UNITED HEALTHCARE COMMUNITY PLAN', 35, 'MMCO', null, '2017Q1', '2018Q4', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('NH', 'New Hampshire', 'MEDI', '43000_Medicaid', 4, 30, 'NEW HAMPSHIRE FDRL', 'NEW HAMPSHIRE FEDERAL MEDICAID ', 33, 'FEDERAL', 'FDRL', '2016Q3', '2019Q2', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('NH', 'New Hampshire', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1657, 'NH MMC', 'NEW HAMPSHIRE MEDICAID MANAGED CARE', 27, 'MMCO', null, '2014Q3', '2017Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('NJ', 'New Jersey', 'MEDI', '43000_Medicaid', 4, 31, 'NEW JERSEY FDRL', 'NEW JERSEY FEDERAL MEDICAID ', 3, 'FEDERAL', 'FDRL', '2017Q2', '2019Q2', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('NJ', 'New Jersey', 'Medi_Exp', '43000_Medicaid Expansion', 72060, 1640, 'NEW JERSEY MED EXP ', 'NEW JERSEY FEE FOR SERVICE MEDICAID EXPANSION  (NX)', 14, 'FEDERAL', null, '2015Q3', '2018Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('NJ', 'New Jersey', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1536, 'NEW JERSEY MMC', 'NEW JERSEY MEDICAID MANAGED CARE', 222, 'MMCO', null, '2014Q4', '2019Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('NJ', 'New Jersey', 'MCO MediEXP', '43001_MCO MediEXP', 77061, 1643, 'NJ EXPANSION FX-MCO', 'NEW JERSEY MEDICAID EXPANSION FX-MCO', 87, 'MMCO', null, '2015Q3', '2018Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('NM', 'New Mexico', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1598, 'NEW MEXICO MMC', 'NEW MEXICO MEDICAID MANAGED CARE', 169, 'MMCO', null, '2014Q3', '2018Q4', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('NV', 'Nevada', 'MEDI', '43000_Medicaid', 4, 33, 'NEVADA FDRL', 'NEVADA FEDERAL MEDICAID ', 83, 'FEDERAL', 'FDRL', '2014Q3', '2019Q4', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('NV', 'Nevada', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1537, 'NEVADA MMC UNITED ', 'NEVADA MMC UNITED HEALTH', 18, 'MMCO', null, '2016Q3', '2018Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('NV', 'Nevada', 'MCO-AMERI', '43001_MCO - Amerigroup', 46, 1538, 'NEVADA MMC AMERIGROU', 'NEVADA MMC AMERIGROUP', 15, 'MMCO', null, '2016Q3', '2017Q4', null, null);
commit;
prompt 100 records committed...
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('NY', 'New York', 'MEDI', '43000_Medicaid', 4, 34, 'NEW YORK FDRL', 'NEW YORK FEDERAL MEDICAID', 260, 'FEDERAL', 'FDRL', '2014Q3', '2019Q1', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('NY', 'New York', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1569, 'NEW YORK MMC', 'NEW YORK MEDICAID MANAGED CARE', 316, 'MMCO', null, '2015Q3', '2019Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('OH', 'Ohio', 'HCPCS', '43000_JCODE - Medicaid', 17, 435, 'OHIO FDRL-J', 'OHIO FEDERAL MEDICAID -J CODES', 51, 'FEDERAL', null, '2016Q1', '2019Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('OH', 'Ohio', 'MEDI', '43000_Medicaid', 4, 35, 'OHIO FDRL', 'OHIO FEDERAL MEDICAID ', 67, 'FEDERAL', 'FDRL', '2014Q4', '2019Q1', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('OH', 'Ohio', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1570, 'OHIO MMC', 'OHIO MEDICAID MANAGED CARE', 377, 'MMCO', null, '2014Q3', '2019Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('OH', 'Ohio', 'HCPCS-MCO', '43001_JCODE - MCO', 23060, 1717, 'OHIO MMC J CODE 3500', 'OHIO MEDICAID MANAGED CARE J-CODE', 238, 'MMCO', null, '2015Q2', '2019Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('OK', 'Oklahoma', 'MEDI', '43000_Medicaid', 4, 36, 'OKLAHOMA FDRL', 'OKLAHOMA FEDERAL MEDICAID', 158, 'FEDERAL', 'FDRL', '2014Q3', '2020Q1', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('OR', 'Oregon', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1552, 'OREGON MMC', 'OREGON MEDICAID MANAGED CARE', 13, 'MMCO', null, '2016Q1', '2018Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('PA', 'Pennsylvania', 'MEDI', '43000_Medicaid', 4, 38, 'PENNSYLVANIA FDRL', 'PENNSYLVANIA FEDERAL MEDICAID', 72, 'FEDERAL', 'FDRL', '2014Q3', '2019Q2', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('PA', 'Pennsylvania', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1526, 'PENNSYLVANIA MMC', 'PENNSYLVANIA MEDICAID MANAGED CARE', 417, 'MMCO', null, '2014Q3', '2020Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('PA', 'Pennsylvania', 'HCPCS-MCO', '43001_JCODE - MCO', 23060, 1686, 'PA MMC JCODES', 'PENNSYLVANIA MEDICAID MANAGED CARE J CODES', 355, 'MMCO', null, '2016Q2', '2019Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('RI', 'Rhode Island', 'HCPCS-MCO', '43001_JCODE - MCO', 23060, 1659, 'RHODE ISLAND MMC HCP', 'RHODE ISLAND MEDICAID MANAGED CARE HCPCS', 7, 'MMCO', null, '2016Q2', '2017Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('SC', 'South Carolina', 'MEDI', '43000_Medicaid', 4, 40, 'SOUTH CAROLINA FDRL', 'SOUTH CAROLINA FEDERAL MEDICAID ', 60, 'FEDERAL', 'FDRL', '2015Q2', '2018Q3', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('SC', 'South Carolina', 'MCO-BLUECH', '43001_MCO - Blue Choice Health', 49, 1529, 'SC MMC BLUE CHOICE ', 'SOUTH CAROLINA MMC BLUE CHOICE HEALTHPLAN', 25, 'MMCO', null, '2017Q4', '2019Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('SC', 'South Carolina', 'MCO-WELLCARE', '43001_MCO - Wellcare', 76064, 1633, 'SC MMC WELLCARE', 'SOUTH CAROLINA MMC WELLCARE', 31, 'MMCO', null, '2014Q4', '2016Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('SC', 'South Carolina', 'MCO-ABSOLU', '43001_MCO- Absolute Total Care', 48, 1528, 'SC MMC ABSOLUTE TOTA', 'SOUTH CAROLINA MMC ABSOLUTE TOTAL CARE', 75, 'MMCO', null, '2015Q3', '2019Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('SC', 'South Carolina', 'MCO-MOLINA', '43001_MCO- Molina', 76066, 1635, 'SC MMC MOLINA', 'SOUTH CAROLINA MEDICAID MANAGED CARE MOLINA', 37, 'MMCO', null, '2015Q4', '2019Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('SD', 'South Dakota', 'MEDI', '43000_Medicaid', 4, 41, 'SOUTH DAKOTA FDRL', 'SOUTH DAKOTA FEDERAL MEDICAID ', 30, 'FEDERAL', 'FDRL', '2014Q3', '2018Q4', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('TN', 'Tennessee', 'MEDI', '43000_Medicaid', 4, 72, 'TENNCARE FDRL', 'TENNESSEE FEDERAL MEDICAID', 220, 'FEDERAL', 'FDRL', '2014Q3', '2019Q3', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('31-12-1993', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('TN', 'Tennessee', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1590, 'TENNESSEE MMC', 'TENNESSEE MEDICAID MANAGED CARE', 1, 'MMCO', null, '2019Q3', '2019Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('TN', null, null, null, null, 72, 'TENNCARE FDRL', 'TENNESSEE FEDERAL MEDICAID', null, null, 'FDRL', null, null, to_date('01-07-1998', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('TN', null, null, null, null, 472, 'TENNCARE FDRL-J', 'TENNESSEE FEDERAL MEDICAID-J CODES', null, null, 'FDRL-J', null, null, to_date('01-07-1998', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('TN', null, null, null, null, 621, 'TENNCARE SUPP', 'TENNESSEE SUPPLEMENTAL', null, null, 'TN SUPP', null, null, to_date('15-12-2003', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('TN', null, null, null, null, 1187, 'TENNESSEE ADAP', 'TENNESSEE ADAP', null, null, 'TN ADAP', null, null, to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('TN', null, null, null, null, 42, 'TENNESSEE FDRL', 'TENNESSEE FEDERAL MEDICAID', null, null, 'FDRL', null, null, to_date('01-07-1990', 'dd-mm-yyyy'), to_date('31-12-1993', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('TN', null, null, null, null, 1590, 'TENNESSEE MMC', 'TENNESSEE MEDICAID MANAGED CARE', null, null, 'TN MMC', null, null, to_date('01-01-2010', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('TX', 'Texas', 'Medi EFMAP', '43000 Medi TX EFMAP', 148060, 1556, 'TEXAS EFMAP', 'TEXAS MEDICAID EFMAP DRUG REBATE', 1, 'FEDERAL', null, '2017Q3', '2017Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('TX', 'Texas', 'MEDI', '43000_Medicaid', 4, 43, 'TEXAS FDRL', 'TEXAS FEDERAL MEDICAID ', 132, 'FEDERAL', 'FDRL', '2014Q3', '2018Q4', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('TX', 'Texas', 'MCO-TXEFMAP', '43001 MCO TX EFMAP', 106060, 1588, 'TEXAS MCO EFMAP', 'TEXAS MCO EFMAP ENHANCED FEDERAL MEDICAL ASSISTANCE', 85, 'MMCO', null, '2015Q3', '2019Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('TX', 'Texas', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1589, 'TEXAS MMC', 'TEXAS MEDICAID MANAGED CARE', 230, 'MMCO', null, '2014Q2', '2019Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('TX', 'Texas', 'HCPCS-MCO', '43001_JCODE - MCO', 23060, 1580, 'TEXAS MMC JCODE', 'TEXAS MEDICAID MANAGED CARE J-CODE', 58, 'MMCO', null, '2016Q2', '2019Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('TX', 'Texas', 'MCO MediEXP', '43001_MCO MediEXP', 77061, 1589, 'TEXAS MMC', 'TEXAS MEDICAID MANAGED CARE', 1, 'MMCO', null, '2015Q2', '2015Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('UT', 'Utah', 'HCPCS', '43000_JCODE - Medicaid', 17, 444, 'UTAH FDRL-J', 'UTAH FEDERAL MEDICAID -J CODES', 13, 'FEDERAL', null, '2016Q1', '2017Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('UT', 'Utah', 'MEDI', '43000_Medicaid', 4, 44, 'UTAH FDRL', 'UTAH FEDERAL MEDICAID ', 13, 'FEDERAL', 'FDRL', '2014Q4', '2018Q4', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('UT', 'Utah', 'HCPCS-MCO', '43001_JCODE - MCO', 23060, 1583, 'UTAH MMC J-CODE', 'UTAH MEDICAID MANAGED CARE J-CODE', 10, 'MMCO', null, '2017Q2', '2018Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('VA', 'Virginia', 'MEDI', '43000_Medicaid', 4, 45, 'VIRGINIA FDRL', 'VIRGINIA FEDERAL MEDICAID  ', 51, 'FEDERAL', 'FDRL', '2015Q1', '2019Q2', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('VA', 'Virginia', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1566, 'VIRGINIA MMC', 'VIRGINIA MEDICAID MANAGED CARE', 295, 'MMCO', null, '2014Q3', '2018Q4', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('VA', 'Virginia', 'MCO Medallion 4', '43001_MCO Medallion 4', 164060, 1785, 'VIRGINIA MED 4 MCO', 'VIRGINIA MEDALLION 4 MCO', 5, 'MMCO', null, '2018Q4', '2020Q1', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('VA', 'Virginia', 'MCO_VA CCC', '43001_MCO_VA CCC Plus', 152060, 1776, 'VIRGINIA CCC PLUS MCO', 'VIRGINIA CCC PLUS MCO', 117, 'MMCO', null, '2018Q1', '2019Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('VT', 'Vermont', 'MEDI', '43000_Medicaid', 4, 46, 'VERMONT FDRL', 'VERMONT FEDERAL MEDICAID ', 2, 'FEDERAL', 'FDRL', '2014Q3', '2014Q3', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('WA', 'Washington', 'MEDI', '43000_Medicaid', 4, 47, 'WASHINGTON FDRL', 'WASHINGTON FEDERAL MEDICAID ', 43, 'FEDERAL', 'FDRL', '2014Q4', '2019Q1', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('WA', 'Washington', 'MCO-SUMARY', '43001 ManagedCare Medi Summary', 45, 1579, 'WASHINGTON MMC', 'WASHINGTON MEDICAID MANAGED CARE', 3, 'MMCO', null, '2018Q2', '2018Q2', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('WI', 'Wisconsin', 'MEDI', '43000_Medicaid', 4, 48, 'WISCONSIN FDRL', 'WISCONSIN FEDERAL MEDICAID ', 121, 'FEDERAL', 'FDRL', '2014Q3', '2019Q3', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('WI', 'Wisconsin', 'WI_Chronic_Diseas', '43003_Wiscon Chronic Disease', 161060, 1565, 'WISCONSIN CHRONIC ', 'WISCONSIN CHRONIC DISEASE', 4, 'SPAP', null, '2018Q2', '2018Q3', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('WV', 'West Virginia', 'HCPCS', '43000_JCODE - Medicaid', 17, 449, 'WEST VIRGINIA FDRL-J', 'WEST VIRGINIA FEDERAL MEDICAID -J CODES', 6, 'FEDERAL', null, '2016Q3', '2017Q4', null, null);
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('WV', 'West Virginia', 'MEDI', '43000_Medicaid', 4, 49, 'WEST VIRGINIA FDRL', 'WEST VIRGINIA FEDERAL MEDICAID ', 19, 'FEDERAL', 'FDRL', '2017Q3', '2018Q4', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
insert into BIVV.MEDI_PGMS_MAP_BIOGEN_T (state, customer_name, program_code, contract_title, contract_number, hcrs_pgm_id, hcrs_pgm_cd, hcrs_pgm_nm, claim_line_cnt, contract_category, hcrs_pgm_catg_cd, min_qtr, max_qtr, hcrs_eff_dt, hcrs_end_dt)
values ('WY', 'Wyoming', 'MEDI', '43000_Medicaid', 4, 50, 'WYOMING FDRL', 'WYOMING FEDERAL MEDICAID', 29, 'FEDERAL', 'FDRL', '2017Q1', '2018Q4', to_date('01-07-1990', 'dd-mm-yyyy'), to_date('01-01-2100', 'dd-mm-yyyy'));
commit;
prompt 147 records loaded

set feedback on
set define on
prompt Done
