DROP TABLE BIVV.CHECK_APPRVL_GRP_CHK_XREF_T CASCADE CONSTRAINTS;

-- Create table
CREATE TABLE BIVV.CHECK_APPRVL_GRP_CHK_XREF_T
(
  apprvl_grp_id NUMBER NOT NULL,
  check_id      NUMBER NOT NULL,
  create_dt     DATE NOT NULL,
  mod_by        VARCHAR2(30) NOT NULL,
  mod_dt        DATE
);

ALTER TABLE BIVV.CHECK_APPRVL_GRP_CHK_XREF_T
  ADD CONSTRAINT FK_CHK_APP_XREF_APPRV_GRPID FOREIGN KEY (APPRVL_GRP_ID)
  REFERENCES BIVV.CHECK_APPRVL_GRP_T (APPRVL_GRP_ID) ON DELETE CASCADE;

