DROP TABLE BIVV.DSPT_CHECK_REQ_T CASCADE CONSTRAINTS;

-- Create table
CREATE TABLE BIVV.DSPT_CHECK_REQ_T
(
  pgm_id          NUMBER(9) NOT NULL,
  ndc_lbl         VARCHAR2(5) NOT NULL,
  period_id       NUMBER(9) NOT NULL,
  reb_clm_seq_no  NUMBER(4) NOT NULL,
  co_id           NUMBER(9) NOT NULL,
  ln_itm_seq_no   NUMBER(4) NOT NULL,
  dspt_seq_no     NUMBER(4) NOT NULL,
  check_id        NUMBER(9) NOT NULL,
  ndc_prod        VARCHAR2(4) NOT NULL,
  ndc_pckg        VARCHAR2(2) NOT NULL,
  paid_amt        NUMBER(12,2) DEFAULT 0 NOT NULL,
  int_amt         NUMBER(9,2) DEFAULT 0 NOT NULL,
  int_owed_amt    NUMBER(9,2),
  int_wrt_off_amt NUMBER(9,2),
  int_owed_flg    CHAR(1) NOT NULL,
  create_dt       DATE,
  mod_dt          DATE,
  mod_by          VARCHAR2(30)
);

CREATE UNIQUE INDEX BIVV.DSPT_CHECK_REQ_T_UN ON BIVV.DSPT_CHECK_REQ_T (NDC_PROD, NDC_PCKG, NDC_LBL, PGM_ID, PERIOD_ID, REB_CLM_SEQ_NO, DSPT_SEQ_NO, CHECK_ID);

-- Create/Recreate primary, unique and foreign key constraints 
CREATE UNIQUE INDEX BIVV.DSPT_CHECK_REQ_T_CHK_ID ON BIVV.DSPT_CHECK_REQ_T (PGM_ID, NDC_LBL, PERIOD_ID, REB_CLM_SEQ_NO, CO_ID, LN_ITM_SEQ_NO, DSPT_SEQ_NO, CHECK_ID);

ALTER TABLE BIVV.DSPT_CHECK_REQ_T
  ADD CONSTRAINT FK_DSPT_CHE_RELATION__DSPT_T FOREIGN KEY (PGM_ID, NDC_LBL, PERIOD_ID, REB_CLM_SEQ_NO, CO_ID, LN_ITM_SEQ_NO, DSPT_SEQ_NO)
  REFERENCES BIVV.DSPT_T (PGM_ID, NDC_LBL, PERIOD_ID, REB_CLM_SEQ_NO, CO_ID, LN_ITM_SEQ_NO, DSPT_SEQ_NO) ON DELETE CASCADE;

-- Create/Recreate check constraints 
ALTER TABLE BIVV.DSPT_CHECK_REQ_T
  ADD CONSTRAINT CKC_INT_OWED_FLG_DSPT_CHE
  CHECK (INT_OWED_FLG IN ('Y','N'));
