DROP TABLE BIVV.VALID_CLAIM_CHK_REQ_T CASCADE CONSTRAINTS;

-- Create table
CREATE TABLE BIVV.VALID_CLAIM_CHK_REQ_T
(
  pgm_id          NUMBER(9) NOT NULL,
  ndc_lbl         VARCHAR2(5) NOT NULL,
  period_id       NUMBER(9) NOT NULL,
  reb_clm_seq_no  NUMBER(4) NOT NULL,
  co_id           NUMBER(9) NOT NULL,
  ln_itm_seq_no   NUMBER(4) NOT NULL,
  check_id        NUMBER(9) NOT NULL,
  ndc_prod        VARCHAR2(4) NOT NULL,
  ndc_pckg        VARCHAR2(2) NOT NULL,
  paid_amt        NUMBER(12,2) DEFAULT 0 NOT NULL,
  int_amt         NUMBER(9,2) DEFAULT 0 NOT NULL,
  int_owed_amt    NUMBER(9,2),
  int_wrt_off_amt NUMBER(9,2),
  int_owed_flg    CHAR(1) NOT NULL,
  create_dt       DATE,
  mod_dt          DATE,
  mod_by          VARCHAR2(30)
);

CREATE UNIQUE INDEX BIVV.VALID_CLAIM_CHK_REQ_UN ON BIVV.VALID_CLAIM_CHK_REQ_T (NDC_PROD, NDC_PCKG, NDC_LBL, PGM_ID, PERIOD_ID, REB_CLM_SEQ_NO, CHECK_ID);

-- since check_id is null in this stage table then just create unique index to similate it
CREATE UNIQUE INDEX VALID_CLAIM_CHK_REQ_T ON BIVV.VALID_CLAIM_CHK_REQ_T (PGM_ID, NDC_LBL, PERIOD_ID, REB_CLM_SEQ_NO, CO_ID, LN_ITM_SEQ_NO, CHECK_ID);

ALTER TABLE BIVV.VALID_CLAIM_CHK_REQ_T
  ADD CONSTRAINT FK_VALID_CL_RELATION__VALID_CL FOREIGN KEY (PGM_ID, NDC_LBL, PERIOD_ID, REB_CLM_SEQ_NO, CO_ID, LN_ITM_SEQ_NO)
  REFERENCES BIVV.VALID_CLAIM_T (PGM_ID, NDC_LBL, PERIOD_ID, REB_CLM_SEQ_NO, CO_ID, LN_ITM_SEQ_NO) ON DELETE CASCADE;

-- Create/Recreate check constraints 
ALTER TABLE BIVV.VALID_CLAIM_CHK_REQ_T
  ADD CONSTRAINT CKC_INT_OWED_FLG_VALID_CL
  CHECK (INT_OWED_FLG IN ('Y','N'));
